name: Bump version and Publish to NPM

on:
  workflow_dispatch:
    inputs:
      version:
        description: version
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Use Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Bump Version
        run: npm version ${{ inputs.version }}

      - name: Push Version
        run: git push origin main --tags
        uses: actions/upload-artifact@v2
        with:
          name: src
          path: ./
